// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_uxAJHJWiG7hO6rAGkwCjQWFuESmw5xc',
    appId: '1:468102825432:web:e13b060e6dc48dca989ead',
    messagingSenderId: '468102825432',
    projectId: 'rich-pich',
    authDomain: 'rich-pich.firebaseapp.com',
    storageBucket: 'rich-pich.appspot.com',
    measurementId: 'G-3WXZMFCJCE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnVG5AxwXNg2C4DaqPPQTWuCeeKGwe058',
    appId: '1:468102825432:android:5790ff6de61cd454989ead',
    messagingSenderId: '468102825432',
    projectId: 'rich-pich',
    storageBucket: 'rich-pich.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBto0kFP4jtbPolsqAGcZrzCYC2kdyOe6Y',
    appId: '1:468102825432:ios:3c3aa29f5815fcff989ead',
    messagingSenderId: '468102825432',
    projectId: 'rich-pich',
    storageBucket: 'rich-pich.appspot.com',
    iosBundleId: 'com.example.richpich',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBto0kFP4jtbPolsqAGcZrzCYC2kdyOe6Y',
    appId: '1:468102825432:ios:3c3aa29f5815fcff989ead',
    messagingSenderId: '468102825432',
    projectId: 'rich-pich',
    storageBucket: 'rich-pich.appspot.com',
    iosBundleId: 'com.example.richpich',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_uxAJHJWiG7hO6rAGkwCjQWFuESmw5xc',
    appId: '1:468102825432:web:e1b6a1923cd8dc3a989ead',
    messagingSenderId: '468102825432',
    projectId: 'rich-pich',
    authDomain: 'rich-pich.firebaseapp.com',
    storageBucket: 'rich-pich.appspot.com',
    measurementId: 'G-6G5XM0TJ72',
  );
}
